# Generated by Django 6.0 on 2025-12-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_proposal_freelancer_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='amount',
        ),
        migrations.AddField(
            model_name='proposal',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Freelancer proposal message', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(limit_choices_to={'role': 'freelancer'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='myapp.project'),
        ),
    ]
